version: 2
dependencies: 
  pre:
  - go get github.com/tcnksm/ghr

deployment:
  release:
    branch: master
    tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
    commands:
      - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` output/

jobs:
  build-job:
    docker:
      - image: cibuilds/hugo:0.28
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/
  release-job:
    docker: 
      - image: cibuilds/hugo:0.28
    branches:
      only:
        - master
    steps:
      - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` ~/project/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - realease-job

