on: 2

jobs:
  build-job:
    docker:
      - image: cibuilds/hugo:0.28
    working_directory: ~/myblog
    steps:
      - checkout
      - run: 
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/
  deploy-job:
    docker: 
      - image: cibuilds/hugo:0.28
    working-directory: ~/myBlog
    steps:
      - run:
          command: |
            git tag
           

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job
