on: 2

jobs:
  build-job:
    docker:
      - image: cibuilds/hugo:0.28
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/
  deploy-job:
    docker: 
      - image: cibuilds/hugo:0.28
    working-directory: ~/project
    steps:
      - run:
          command: |
            if[ "$CIRCLE_BRANCH" = "master"]; then
              echo "Hello From master"
            fi
           

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
  release-deploy:
    jobs:
      - deploy-job
